name: 'run-specflow-tests'
description: 'Github action to run SpecFlow tests and create LivingDoc artifact'
author: 'cryptic-wizard'
branding:
  icon: check-square
  color: green

inputs:
  test-assembly-dll:
    description: "Relative path of <MySpecflowProject.dll> (example: MySpecflowProject/bin/Debug/netcoreapp3.1/MySpecflowProject.dll)"
    required: true
  test-execution-json:
    description: "Relative path of <MySpecflowProjectTestExecution(s).json> (example: MySpecflowProject/bin/Debug/netcoreapp3.1/TestExecution.json)"
    required: true
  output-html:
    description: "Name of Specflow LivingDoc output file (must end with .html)"
    required: false
    default: 'LivingDoc.html'
  build-verbosity:
    description: "Verbosity of the Dotnet App Build (default = minimal)"
    required: false
    default: 'minimal'
  test-verbosity:
    description: "Verbosity of the SpecFlow Test Execution (default = normal)"
    required: false
    default: 'normal'
  no-build:
    description: "Set to true to disable dotnet build and dotnet restore"
    required: false
    default: 'false'
  dotnet-version:
    description: "Version of dotnet (example: netcoreapp3.1, net5.0)"
    required: false
    default: ''
  #upload-artifact: TODO
    #description: "Set to false to disable uploading <LivingDoc.html> artifact automatically"
    #required: false
    #default: 'true'
runs:
  using: composite
  steps:
    #- name: Checkout
      #uses: actions/checkout@v2
    #- name: Setup .NET Core
      #uses: actions/setup-dotnet@v1
      #with:
        #dotnet-version: 3.1.x
    - name: BuildDotnetApp
      run: |
        if [ ${{ inputs.no-build }} == 'true' ]; then
          echo 'Build Skipped'
        elif [ ${{ inputs.dotnet-version }} == '' ]; then
          dotnet build --verbosity ${{ inputs.build-verbosity }}
        else
          dotnet build --verbosity ${{ inputs.build-verbosity }} -f ${{ inputs.dotnet-version }}
        fi
      shell: bash
    - name: RunSpecFlowTests
      run: |
        if [ ${{ inputs.dotnet-version }} == '' ]; then
          dotnet test --no-build --verbosity ${{ inputs.test-verbosity }}
        else
          dotnet test --no-build --verbosity ${{ inputs.test-verbosity }} -f ${{ inputs.dotnet-version }}
        fi
      shell: bash
    - name: GenerateSpecFlowLivingDoc
      run: |
        dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
        livingdoc test-assembly ${{ inputs.test-assembly-dll }} -t ${{ inputs.test-execution-json }} -o ${{ inputs.output-html }}
      shell: bash
    #- name: 'Publish Specflow Test Results'
      #uses: actions/upload-artifact@v2
      #with:
        #name: 'Specflow Test Results'
        #path: ${{ output-html }}
