name: 'Run Specflow Tests'
description: 'Github action to run SpecFlow tests and create LivingDoc artifact'
inputs:
  test-assembly-dll:
    description: "Relative path of <MySpecflowProject.dll> (example: MySpecflowProject/bin/Debug/netcoreapp3.1/MySpecflowProject.dll)"
    required: true
  test-execution-json:
    description: "Relative path of <MySpecflowProjectTestExecution(s).json> (example: MySpecflowProject/bin/Debug/netcoreapp3.1/TestExecution.json)"
    required: true
  output-html:
    description: "Name of Specflow LivingDoc output file (must end with .html)"
    required: false
    default: 'LivingDoc.html'
  verbosity:
    description: "Verbosity of the SpecFlow Test Execution (default = normal)"
    required: false
    default: 'normal'
  no-build:
    description: "Set to false to disable dotnet build and dotnet restore"
    required: false
    default: 'true'
  #upload-artifact: TODO
    #description: "Set to true to upload <LivingDoc>.html artifact automatically"
    #required: false
    #default: 'false'
#outputs:
  #output-file: TODO
    #description: "Full path of <LivingDoc.html>"
    #value: ${{ steps.run-specflow-tests.outputs.output-file }}
runs:
  using: composite
  steps:
    - name: 'Run Specflow Tests'
      run: |
        if [ ${{ inputs.no-build }} == 'false' ]; then dotnet test --no-build --verbosity ${{ inputs. verbosity }}; else dotnet test --verbosity ${{ inputs. verbosity }}; fi
        #dotnet test --verbosity ${{ inputs.verbosity }}
        dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
        livingdoc test-assembly ${{ inputs.test-assembly-dll }} -t ${{ inputs.test-execution-json }} -o ${{ inputs.output-html }}
        #if [ ${{ inputs.upload-artifact }} == 'true' ]; then UPLOAD; fi
      shell: bash