name: .NET Core

on:
  push:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - uses:  impolitetulip/run-specflow-tests@v0.0
      with:
        test-assembly-dll: RunSpecflowTests/bin/Debug/netcoreapp3.1/RunSpecflowTests.dll
        test-execution-json: RunSpecflowTests/bin/Debug/netcoreapp3.1/TestExecution.json
        output-html: MyTestResults.html